### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by josegl** [firecat53/keepmenu#1]
Hi I've installed keepmenu in my system because I think it is a great idea, but I am having problems running it.

Distro: Ubuntu 17.10 x64 updated.

What happens:
1. type keepmenu in a terminal
2. dmenu opens with a blue background and white foreground label `entries`
3. start typing in dmenu, nothing happens neither in dmenu nor terminal output
4. type something that actually may exist in the database, press enter:
```
Traceback (most recent call last):
  File "/usr/local/bin/keepmenu", line 279, in <module>
    run()
  File "/usr/local/bin/keepmenu", line 263, in run
    keepass = open_database([i for i in databases if i[0] == sel.strip()][0])
IndexError: list index out of range
```

What could be happening?

**Comment by firecat53** [comment]
Did you copy config.ini to ~/.config/keepmenu/config.ini and edit it to include your database and keyfile paths?

That's my first guess...maybe post config.ini here if it still doesn't work.

Thanks for testing it out for me!

Scott

**Comment by josegl** [comment]
Yes I did copy `config.ini` into `~/.config/keepmenu/config.ini`.
I configured the database path, but no keyfile because my database is not protected with a key file. I often use a GPG key and saw that the `config.ini` had a setting for the GPG key, so I set this setting too, I've assumed that it is to save the data read from the database encrypted in memory.

And, about the version, it is 0.2.1
The installation process was:
1. First install dependencies manually with `pip`, those that couldn´t be installed like `pygpgme` was because missing dependencies that I installed too, and when all the dependencies were installed, then I installed keepmenu with `pip`.

Thank you very much for your effort 😃 💪

**Comment by josegl** [comment]
Here you have the config.ini file:

```
[dmenu]
fn = -*-terminus-medium-*-*-*-16-*-*-*-*-*-*-*
dmenu_command = /usr/bin/dmenu
# # Note that dmenu_command can contain arguments as well like `rofi -width 30`
# # Rofi and dmenu are set to case insensitive by default `-i`
# l = number of lines to display (default 24 max)
# fn = font string
# nb = normal background (name, #RGB, or #RRGGBB)
# nf = normal foreground
# sb = selected background
# sf = selected foreground
# b =  (just set to empty value and menu will appear at the bottom
# m = number of monitor to display on
# pinentry = Pinentry command

# # override normal foreground and background colors (dmenu) or use the
# # -password option (rofi) to obscure passphrase entry
# [dmenu_passphrase]
# nf = #222222
# nb = #222222
# rofi_obscure = True

[database]
database_n = ~/password_database.kdbx
# database_n = <path/to/database> ~ for $HOME is ok
# keyfile_n = <path/to/keyfile>
password_n = "my database password (this is not my actual password of course xD)"
# password_n = database password  **INSECURE**
gpg_key = 397A3D64BA12F73501259FA9761AECD074F4AA95
# gpg_key = <fingerprint - last 8 characters is fine>
# pw_cache_period = <hours to cache database password>
```

On monday I will try the development version at work that is were I'm testing it, at home I use the windows 10 integrated ubuntu bash, I don't have a Linux setup yet (I'm tons of hours every week at work progamming, testing tools on linux, and then at home I prefer to do other kind of stuff), so I cannot test right now.
But anyway, I will try out on Monday the development version. Oh, maybe I have my config.ini file with a typo or something wrong there.

Thank you for your interest and work 👍

**Comment by firecat53** [comment]
Ah, that's what I thought...the database entries should be 

database_1 = path
keyfile_1 = path

I put the _n just as an indication that it could be numbered. I can see how that might not be clear!

The newest version will generate a basic configuration for you and prompt for initial database and keyfile paths. 

Thanks again for trying it out!

Scott

**Comment by josegl** [comment]
Oh I see, I thought the `_n` notation was something related to the internals of the program.

Cool idea about the promt for the database password and keep cached for six hours with GPG.

Have you think about using other format for the config file like json or yaml? I think it could be easier to understand, and to parse too.
something like:
```javascript
{
  "dmenu": {
    "command": "/usr/local/bin/dmenu",
    "lines": 24,
    "font": "whatever"
    "colors": {
       //color stuff here
    },
  },
  "databases": [
    {
      "path": "the path",
      "key_file": null, //default value
    },
  ]
}
```
Of course this is just an example.

**Comment by firecat53** [comment]
I like the ConfigParser module because it's already got builtin features for reading and writing to the config file, and easily detecting sections and fields.

The next generation of keepmenu I'm working on will actually have a daemon mode that will run in the background to reduce startup time and make the GPG feature unnecessary for caching the passphrase.
