### ISSUE TITLE
Error on opening databse - Connection Refused

### ISSUE THREAD

**Issue by lyndhurst** [firecat53/keepmenu#134]
I never used `keepmenu` before, I just wanted to try it out.

I installed on an Ubuntu 18 machine using `pip install`, and a fresh manjaro install using the `AUR` repo.
I have tried a different database on each machine, both `.kdbx` created using `keepassxc`.

Even if the error stack trace is different, the error looks like #77 so I checked, I have `pykeepass` 4.0 installed on both machines.

`keepmenu -h` is working fine, but `keepmenu -d path/to/db.kdbx` prints the following stack trace:

```
Traceback (most recent call last):
  File "/home/****/.local/lib/python3.6/site-packages/keepmenu/__main__.py", line 171, in main
    manager = client()
  File "/home/****/.local/lib/python3.6/site-packages/keepmenu/__main__.py", line 76, in client
    mgr.connect()
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 489, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/****/.local/bin/keepmenu", line 8, in <module>
    sys.exit(main())
  File "/home/****/.local/lib/python3.6/site-packages/keepmenu/__main__.py", line 178, in main
    run(**args)
  File "/home/****/.local/lib/python3.6/site-packages/keepmenu/__main__.py", line 126, in run
    dmenu = DmenuRunner(server, **kwargs)
  File "/home/****/.local/lib/python3.6/site-packages/keepmenu/keepmenu.py", line 275, in __init__
    self.database, self.open_databases = get_database(**kwargs)
  File "/home/****/.local/lib/python3.6/site-packages/keepmenu/keepmenu.py", line 163, in get_database
    dbs[0].pword = get_passphrase()
  File "/home/****/.local/lib/python3.6/site-packages/keepmenu/keepmenu.py", line 249, in get_passphrase
    password = dmenu_select(0, "Password")
  File "/home/****/.local/lib/python3.6/site-packages/keepmenu/menu.py", line 74, in dmenu_select
    input=inp)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output
```

Thank you for your time.

**Comment by firecat53** [comment]
I'm suspecting that the python version on Ubuntu 18.04 is too old. Keepmenu requires >= Version 3.7. You can use something like pipx + pyenv to install it inside a virtualenv with a newer python version.

**Comment by vaygr** [comment]
I have 2 setups:

1. [keepmenu](https://aur.archlinux.org/packages/keepmenu) package from AUR on Manjaro, but [keepmenu-git](https://aur.archlinux.org/packages/keepmenu-git) should work just fine. This one is using system Python 3.10.5.
2. keepmenu installed via pip with [pyenv](https://github.com/pyenv/pyenv) + [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv) using Python 3.7.13 on some very old source-based Linux distro installation (2015 or so).

In both cases keepmenu is 1.3.1 and pykeepass is 4.0.3. All work well.

**Comment by lyndhurst** [comment]
You are right @firecat53 , for the ubuntu machine, I have python 3.6.9 installed. I will try to look into pyenv and pipx this weekend.
For my manjaro setup, I am a bit more perplex because all the versions I got installed match what @vaygr describes, the machine is freshly installed so maybe I am missing something...
Thank you both for the help.

**Comment by vaygr** [comment]
@lyndhurst also make sure `dmenu` is installed or have alternative menu command configured as its replacement in `~/.config/keepmenu/config.ini`.

**Comment by lyndhurst** [comment]
@vaygr textbook case of tunnel vision! The manjaro machine was so fresh, I did not even think of installing rofi; whilst I did tweak the keepmenu config file to make sure it was using it on the ubuntu machine!

Thanks again then, and sorry for being a bit too quick to ask for help!

`:emoji shamefully hitting its forehead with its hand:`
