### ISSUE TITLE
{TAB} and {ENTER} don't work with ydotool

### ISSUE THREAD

**Issue by munnik** [firecat53/keepmenu#148]
Hi,

I'm trying to use keepmenu with Wayland/Hyprland and I got an issue with entering usernames and passwords. My config is:

```ini
[dmenu]
#dmenu_command = rofi -dmenu -theme catppuccin-mocha -i
dmenu_command = rofi -dmenu -i -theme Indego

[dmenu_passphrase]
obscure = True

[database]
database_1 = ~/Documents/KeePassXC/default.kdbx
autotype_default_1 = {USERNAME}{TAB}{PASSWORD}{ENTER}

pw_cache_period_min = 5
editor = nvim
terminal = kitty
type_library = ydotool
```

I'm able to run keepmenu and select an entry from the list. The username and password is then type into the active window. But the {TAB} and {ENTER} options don't seem to do anything. I've verified that ydotool is working as intended by running 
```
ydotool type munnik; ydotool key 15:1 15:0; ydotool type secret; ydotool key 28:1 28:0
``` 
in my shell. It outputs (followed by an enter)
```
munnik	secret
``` 
Adding {SPACE} in the config gives a space in the output.

Any tips on how to further debug what is going on?

**Comment by firecat53** [comment]
My initial suspicion is that you're using Rofi on a Wayland system. To my
knowledge, Rofi doesn't yet directly support Wayland. Try using bemenu or fuzzel
and see if you get the same result. Rofi is likely using xwayland, which can
have weird side effects in this application.

**Comment by munnik** [comment]
I'm using https://github.com/lbonn/rofi which is a fork of rofi created for wayland. I just tried bemenu ```dmenu_command = bemenu -i``` with the same result, no tab and return are typed.

**Comment by firecat53** [comment]
* What versions of keepmenu and ydotool are you using? From repos or installed
  manually?
* Which distro?
* Have you tried a different terminal?

I use ydotool with Sway and bemenu daily, so I'm having trouble figuring out
where the issue might be.

**Comment by munnik** [comment]
- keepmenu v1.2.2
- ydotool 1.0.4
both from NixOS 23.05 repro. I've tried Kitty and VIM but also Librewolf.

I now see the release notes of 1.3.0 ```Use keycodes for typing with ydotool by @psvenk in https://github.com/firecat53/keepmenu/pull/111```. I think that is my problem. Will try to compile the new version of keepmenu.

**Comment by firecat53** [comment]
Oops, sorry didn't see your comment before my edit.

Ah, yep, that's the issue! That's a quite old version of keepmenu.

**Comment by munnik** [comment]
I'm new to NixOS so maybe I'm doing something wrong:

```
$ nix build
error: builder for '/nix/store/y79cj4l346qlfxi5pnvs8nb44rrkxghg-keepmenu.drv' failed with exit code 1;
       last 10 log lines:
       >   full command: /nix/store/2c7sgx69p6mmp76cvmi5j6c72dj76jj8-python3-3.10.12/bin/python3.10 /nix/store/7xyrvds2v73visz9zjy32r3xazm8sn6y-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /build/tmpm2p197h4
       >   cwd: /build/38gz3y30zjw6v2lkgnbvqn7x71qakwnw-source
       >   Preparing metadata (pyproject.toml) ... error
       > error: metadata-generation-failed
       >
       > × Encountered error while generating package metadata.
       > ╰─> See above for output.
       >
       > note: This is an issue with the package mentioned above, not pip.
       > hint: See above for details.
       For full logs, run 'nix log /nix/store/y79cj4l346qlfxi5pnvs8nb44rrkxghg-keepmenu.drv'.
```

```
$ nix log /nix/store/y79cj4l346qlfxi5pnvs8nb44rrkxghg-keepmenu.drv
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/p6hr2k79r0n68sk1708aak631ymh7s1k-38gz3y30zjw6v2lkgnbvqn7x71qakwnw-source
source root is 38gz3y30zjw6v2lkgnbvqn7x71qakwnw-source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file 38gz3y30zjw6v2lkgnbvqn7x71qakwnw-source/tests/tests.py
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing pipBuildPhase
Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Processing /build/38gz3y30zjw6v2lkgnbvqn7x71qakwnw-source
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/nix/store/7xyrvds2v73visz9zjy32r3xazm8sn6y-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/nix/store/7xyrvds2v73visz9zjy32r3xazm8sn6y-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/nix/store/7xyrvds2v73visz9zjy32r3xazm8sn6y-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "/nix/store/23ql691faqjiqb4s2627yxd5p0a4f789-python3.10-hatchling-1.18.0/lib/python3.10/site-packages/hatchling/build.py", line 56, in build_wheel
      return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
    File "/nix/store/23ql691faqjiqb4s2627yxd5p0a4f789-python3.10-hatchling-1.18.0/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 93, in build
      self.metadata.validate_fields()
    File "/nix/store/23ql691faqjiqb4s2627yxd5p0a4f789-python3.10-hatchling-1.18.0/lib/python3.10/site-packages/hatchling/metadata/core.py", line 243, in validate_fields
      _ = self.version
    File "/nix/store/23ql691faqjiqb4s2627yxd5p0a4f789-python3.10-hatchling-1.18.0/lib/python3.10/site-packages/hatchling/metadata/core.py", line 128, in version
      self._version = self._get_version()
    File "/nix/store/23ql691faqjiqb4s2627yxd5p0a4f789-python3.10-hatchling-1.18.0/lib/python3.10/site-packages/hatchling/metadata/core.py", line 226, in _get_version
      version = self.hatch.version.cached
    File "/nix/store/23ql691faqjiqb4s2627yxd5p0a4f789-python3.10-hatchling-1.18.0/lib/python3.10/site-packages/hatchling/metadata/core.py", line 1415, in cached
      raise type(e)(message) from None
  LookupError: Error getting the version from source `vcs`: setuptools-scm was unable to detect version for /build/38gz3y30zjw6v2lkgnbvqn7x71qakwnw-source.

  Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

  For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /nix/store/2c7sgx69p6mmp76cvmi5j6c72dj76jj8-python3-3.10.12/bin/python3.10 /nix/store/7xyrvds2v73visz9zjy32r3xazm8sn6y-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /build/tmpm2p197h4
  cwd: /build/38gz3y30zjw6v2lkgnbvqn7x71qakwnw-source
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by vaygr** [comment]
This is related to #147

**Comment by firecat53** [comment]
Try `nix build path:`. That should work out of the box.

**Comment by firecat53** [comment]
Also, `pipx` is a nice tool for installing simple utilities like this without needing to download the source. `pipx install keepmenu`. It's obviously imperative, so doesn't fit with the Nix Way, but...it works :shrug:

**Comment by munnik** [comment]
The 1.4.0 version resolved the issue! I will ask the maintainer of the keepmenu package in the NixOS if he/she can update the version. Thanks for the support!
