### ISSUE TITLE
Add simple ability to show passwords via CLI

### ISSUE THREAD

**Issue by vaygr** [firecat53/keepmenu#150]
keepmenu can already read keepass databases, so implementation of this should be trivial. We probably don't need to spin up a daemon for this and forego caching altogether.

Rationale: software like `mutt` or `weechat` allow you to specify commands to decrypt data that can be used for passphrase purposes (SMTP/POP3/IMAP/IRC auth, certificate decryption, etc.). Typically you would use plain `gpg` for this: `gpg --batch -q --decrypt ~/.config/mutt/master.gpg`. Or a password manager like `pass`: `pass show weechat/passphrase`. This forces to either use another password manager or different encrypted files, which promotes secret sprawl.

Furthermore, solving this will unlock usage in software like [chezmoi](https://www.chezmoi.io/) for secret retrieval: https://www.chezmoi.io/reference/templates/secret-functions/secret/. Maybe it'll deserve its own function for chezmoi in the future.

This way all secrets can be kept in one database and retrieved by the same tool.

The proposal is to add `-s`/`--show` "mode" with an argument to display a password entry at the specified path. This can be extended to other fields, but I think just the password entry could be a good start.

**Comment by firecat53** [comment]
Sounds reasonable and likely not too difficult.

**Comment by vaygr** [comment]
Second.

I think how `keepassxc-cli` works is you pass the database and entry and it asks for the password interactively:

```
$ keepassxc-cli show -h
Missing positional argument(s).

Usage: keepassxc-cli show [options] database entry
Show an entry's information.

Options:
  -q, --quiet                    Silence password prompt and other secondary
                                 outputs.
  -k, --key-file <path>          Key file of the database.
  --no-password                  Deactivate password key for the database.
  -y, --yubikey <slot[:serial]>  Yubikey slot and optional serial used to
                                 access the database (e.g., 1:7370001).
  -t, --totp                     Show the entry's current TOTP.
  -a, --attributes <attribute>   Names of the attributes to show. This option
                                 can be specified more than once, with each
                                 attribute shown one-per-line in the given
                                 order. If no attributes are specified, a
                                 summary of the default attributes is given.
  -s, --show-protected           Show the protected attributes in clear text.
  --all                          Show all the attributes of the entry.
  --show-attachments             Show the attachments of the entry.
  -h, --help                     Display this help.

Arguments:
  database                       Path of the database.
  entry                          Name of the entry to show.
```

That would be most secure. Then, for example, when chezmoi [uses it](https://www.chezmoi.io/reference/templates/keepassxc-functions/), it would cache the password in plaintext in case of fetching multiple entries before exiting.

**Comment by firecat53** [comment]
Chezmoi would cache the keepass database password? How is that passed? Or are saying it will cache the chezmoi db password that you retrieve from keepmenu?

**Comment by vaygr** [comment]
Yes, chezmoi would cache the keepass database password. In case of keepassxc-cli I think [they use tty](https://github.com/twpayne/chezmoi/blob/5f8e79614b1765ae43adde996a78bc8cc645be1b/internal/cmd/keepassxctemplatefuncs.go#L228).

**Comment by firecat53** [comment]
Sorry if I'm being dense, but it seems like you're looking for something different than I'm understanding.

I'm thinking: `keepmenu --show "Joe's Grill" -d db.kdbx` -> Prompts for passphrase on the CLI (not launcher) -> outputs Joe's Grill password to stdout (or to clipboard if the -C flag is passed). 
- If the database is not passed and there is more than one db listed in the config->error.
- If the keyfile isn't included in the config file-> error
- If keepmenu is already running and one of the open db names is passed with -d ->outputs password.

I'm not understanding your intended workflow.

**Comment by vaygr** [comment]
Yes, what you've described is exactly how I see it.

Above I showed how keepassxc-cli integrates with chezmoi, so when this functionality is implemented in keepmenu, we could implement/ask about chezmoi integration, so keepmenu could be used in chezmoi templating system to fetch passwords/attachments.

**Comment by firecat53** [comment]
Ah, ok :smile: Thanks for the clarification!

I'm almost done, although I still have to see how complex it will be to detect the already open databases.

**Comment by firecat53** [comment]
Initial working idea on the `run_once` branch. It doesn't have detection of currently open db's.

**Comment by vaygr** [comment]
OK, simple cases work, that's great:

```
$ keepmenu -s "DigiCert"
Password:
changeme
```

A bit more complex need massaging though:

```
$ keepmenu -s "Duo"
Password:
Multiple entries found matching 'Duo'. Please be more specific.
  - Hosting/Auth/Duo (user1@domain1.tld)
  - Hosting/Auth/Duo (user2@domain2.tld)
```

I have a multi-level topology here, so how can I be more specific? `keepmenu -s "Duo (user1@domain1.tld)"` didn't work, but also..:

We need to be able to distinguish between these two even with the same usernames:

```
- Hosting/Auth/Duo (user1@domain1.tld)
- Work/Place/Duo (user1@domain1.tld)
```

Lastly, even if I had just one entry in the previous example but need to distinguish between the same entry in a different folder, `keepmenu -s "Hosting/Auth/Duo"` didn't work for me either.

**Comment by firecat53** [comment]
I'm really close now (6 months later 🙄).
- You can enter portions of multiple search terms and it should find the entries (e.g. 'Work Duo' or 'Host Duo user2' both should find the correct entries.
- Add a --no-prompt flag to disable prompting for the db password if desired (e.g. password is provided by password_cmd)
- If the daemon is running, it will use without prompting for a password either the currently active db if -d is not passed, or the db provided by -d.
- If the daemon is not running, password prompting occurs on the command line.

The one remaining issue to solve is that if the daemon is running, the password prompting happens in the GUI instead of the CLI, so you have to run the command twice to return the correct value, as the first run returns from the client run before the db is unlocked.

**Comment by firecat53** [comment]
Ok, I think it finally works the way I want. Test (`run_once` branch) with a couple of databases including different search strings and dbs that need and don't need passwords. Thanks!

**Comment by vaygr** [comment]
@firecat53 apologies for the delay here. One significant time off after another.

So this case doesn't work for me still:

```
  - Hosting/Auth/Duo (user1@domain1.tld)
  - Hosting/Auth/Duo (user2@domain2.tld)
```

- `Hosting` returns entries
- `Hosting/Auth` returns entries
- `Hosting/Auth/Duo` returns nothing 😳
- `Hosting Duo user2` returns nothing

**Comment by vaygr** [comment]
Yes, this is still not working, and yes, passwords are set for both entries.

There's no daemon, I tested it with `.venv/bin/keepmenu -s "Hosting/Auth/Duo"`.

Testing on commit `23e1a6c`.

Both entries are located at: Root > Hosting > Auth.

**Comment by firecat53** [comment]
Are the entries both titled 'Duo' or is there another group 'Duo' under 'Auth' ?

**Comment by firecat53** [comment]
I added (and just pushed) entries to tests.kdbx that seem to match what you describe and I'm still not seeing the same behavior. Searches work correctly. Can you look at those entries and see how they differ from yours?

**Comment by The-Compiler** [comment]
I was asked to give this a try, but I can't seem to figure out what password to use for `tests/test.kdbx` 😅

I tried using `password` as I saw that in the tests file, but that ends up with an "Enter password:" keepmenu prompt popping up, as well as this exception:

```pytb
$ .venv/bin/keepmenu -s "Hosting/Auth/Duo" -d tests/test.kdbx
Password: 
Traceback (most recent call last):
  File "/home/florian/proj/keepmenu/.venv/bin/keepmenu", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/florian/proj/keepmenu/keepmenu/__main__.py", line 322, in main
    result = manager.receive_show_result()  # pylint: disable=no-member
  File "/home/florian/.local/share/uv/python/cpython-3.14.2-linux-x86_64-gnu/lib/python3.14/multiprocessing/managers.py", line 730, in temp
    token, exp = self._create(typeid, *args, **kwds)
                 ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/.local/share/uv/python/cpython-3.14.2-linux-x86_64-gnu/lib/python3.14/multiprocessing/managers.py", line 612, in _create
    id, exposed = dispatch(conn, None, 'create', (typeid,)+args, kwds)
                  ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/.local/share/uv/python/cpython-3.14.2-linux-x86_64-gnu/lib/python3.14/multiprocessing/managers.py", line 95, in dispatch
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.14/multiprocessing/managers.py", line 213, in _handle_request
    result = func(c, *args, **kwds)
  File "/usr/lib/python3.14/multiprocessing/managers.py", line 383, in create
    self.registry[typeid]
    ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'receive_show_result'
---------------------------------------------------------------------------
```

**Comment by firecat53** [comment]
Thanks for trying! Yes, password is the test db password. Prob a dumb question but did you delete and redo .venv before trying this? 
Edit: Also, did you kill the existing running process?

**Comment by vaygr** [comment]
@firecat53 I'm curious what your dependencies are:

```txt
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
cffi==1.17.1
construct==2.10.70
evdev==1.9.1
lxml==5.3.1
pycparser==2.22
pycryptodomex==3.21.0
pykeepass==4.1.1.post1
pynput==1.8.0
pyotp==2.9.0
python-xlib==0.33
six==1.17.0
wheel==0.45.1
```

anything significantly different?

**Comment by vaygr** [comment]
@firecat53 it's interesting that `keepmenu -s "Hosting/Auth/Duo" -d tests/test.kdbx` returns 2 entries for me, compared to yours 4:

```sh
$$ keepmenu -s "Hosting/Auth/Duo" -d tests/test.kdbx
Password:
Multiple entries found matching 'Hosting/Auth/Duo'. Please be more specific.
  - Hosting/Auth/Duo/user1 (user1@domain1.tld)
  - Hosting/Auth/Duo/user2 (user2@domain2.tld)
```

However `keepmenu -s "Hosting/Auth" -d tests/test.kdbx` returns them all:

```sh
$$ keepmenu -s "Hosting/Auth" -d tests/test.kdbx
Password:
Multiple entries found matching 'Hosting/Auth'. Please be more specific.
  - Hosting/Auth/Duo/user1 (user1@domain1.tld)
  - Hosting/Auth/Duo/user2 (user2@domain2.tld)
  - Hosting/Auth/Duo (user1@domain1.tld)
  - Hosting/Auth/Duo (user2@domain2.tld
```

**Comment by firecat53** [comment]
I think the issue was there were two root groups called Hosting and for whatever reason that was causing different responses depending on the machine and maybe moon phase?? I adjusted the test.kdbx entries. 

Please try again and hopefully it will match this time!! @The-Compiler were you able to try again, ensuring the previous daemon was killed?

```
❯ keepmenu -d tests/test.kdbx -s "user1"
Multiple entries found matching 'user1'. Please be more specific.
  - Hosting/Auth/Duo (user1@domain1.tld)
  - Work/Auth/Duo (user1@domain1.tld)
  - Work/HR/Duo (user1@domain1.tld)

keepmenu on  run_once [?] via 🐍 v3.13.11 (.venv) via ❄️  impure (nix-shell-env)
❯ keepmenu -d tests/test.kdbx -s "user2"
Multiple entries found matching 'user2'. Please be more specific.
  - Hosting/Auth/Duo (user2@domain2.tld)
  - Work/Auth/Duo (user2@domain2.tld)

keepmenu on  run_once [?] via 🐍 v3.13.11 (.venv) via ❄️  impure (nix-shell-env)
❯ keepmenu -d tests/test.kdbx -s "work user1"
Multiple entries found matching 'work user1'. Please be more specific.
  - Work/Auth/Duo (user1@domain1.tld)
  - Work/HR/Duo (user1@domain1.tld)

keepmenu on  run_once [?] via 🐍 v3.13.11 (.venv) via ❄️  impure (nix-shell-env)
❯ keepmenu -d tests/test.kdbx -s "duo user1"
Multiple entries found matching 'duo user1'. Please be more specific.
  - Hosting/Auth/Duo (user1@domain1.tld)
  - Work/Auth/Duo (user1@domain1.tld)
  - Work/HR/Duo (user1@domain1.tld)

keepmenu on  run_once [?] via 🐍 v3.13.11 (.venv) via ❄️  impure (nix-shell-env)
❯ keepmenu -d tests/test.kdbx -s "work hr user1"
A)][.c4qVJpd%OF~q<H%\K0~\UW-kgW2N'lSI3Oh8;"mNi)==
```

**Comment by vaygr** [comment]
```sh
$$ keepmenu -s "work user1" -d tests/test.kdbx
Password:
No entries found matching 'work user1'
$$ keepmenu -s "duo user1" -d tests/test.kdbx
Password:
No entries found matching 'duo user1'
```

Black magic.

**Comment by firecat53** [comment]
OMG this is driving me nuts!! Can you see the entries in the database? Is it just the search that isn't working?

**Comment by vaygr** [comment]
Yeah. I just tested with keepassxc and `keepmenu -d tests/test.kdbx`.

**Comment by vaygr** [comment]
I didn't see your response to https://github.com/firecat53/keepmenu/issues/150#issuecomment-3844347169. Are your deps different? Maybe try them in `requirements.txt`?

**Comment by firecat53** [comment]
Some differences, but I'm not sure what would affect the fairly simple finding logic. I also replaced my requirements.txt with yours and did a fresh venv with `uv pip install -e .`. I'm still seeing the same results. I also used both your requirements.txt and the default requirements.txt on a stock Arch VM and got the same results. Here's my `uv pip list` output:

```
Package              Version      Editable project location
-------------------- ------------ -------------------------------------------------------
anyio                4.12.1
argon2-cffi          25.1.0
argon2-cffi-bindings 25.1.0
backports-zstd       1.3.0
certifi              2026.1.4
cffi                 2.0.0
click                8.3.1
construct            2.10.70
cryptography         46.0.4
distlib              0.4.0
evdev                1.9.3
filelock             3.20.3
h11                  0.16.0
hatch                1.16.3
hatchling            1.28.0
httpcore             1.0.9
httpx                0.28.1
hyperlink            21.0.0
idna                 3.11
jaraco-classes       3.4.0
jaraco-context       6.1.0
jaraco-functools     4.4.0
jeepney              0.9.0
keepmenu             1.4.5.dev13  /home/firecat53/docs/family/scott/src/projects/keepmenu
keyring              25.7.0
lxml                 6.0.2
markdown-it-py       4.0.0
mdurl                0.1.2
more-itertools       10.8.0
packaging            26.0
pathspec             1.0.4
pexpect              4.9.0
pip                  25.3
platformdirs         4.5.1
pluggy               1.6.0
ptyprocess           0.7.0
pycparser            3.0
pycryptodomex        3.23.0
pygments             2.19.2
pykeepass            4.1.1.post1
pynput               1.8.1
pyotp                2.9.0
pyproject-hooks      1.2.0
python-xlib          0.33
rich                 14.3.2
secretstorage        3.5.0
shellingham          1.5.4
six                  1.17.0
tomli-w              1.2.0
tomlkit              0.14.0
trove-classifiers    2026.1.14.14
userpath             1.9.2
uv                   0.10.0
virtualenv           20.36.1
```

What commit are you installing on? I just rebased `run_once` on dev to add some other unrelated fixes, fyi. Current `run_once` HEAD is 5228919.

**Comment by vaygr** [comment]
I'm testing 5228919, same unfortunately.

**Comment by firecat53** [comment]
I'm running out of ideas. What distro are you using? Can you test in a clean VM?

**Comment by vaygr** [comment]
Well, that won't help with explaining why this setup is not working.

Maybe you could add some debug info or point at where I should start troubleshooting to see at what point there might be issues?

**Comment by firecat53** [comment]
Added some debugging code. Let me know ideas for any additional. Here's my output:

```
✦ ❯ KEEPMENU_DEBUG=1 keepmenu -s "work user1" -d tests/test.kdbx
DEBUG: Search string: 'work user1'
DEBUG: Search string (lower): 'work user1'
DEBUG: Search terms: ['work', 'user1']
DEBUG: Total entries to search: 19
DEBUG: --- All entries ---
DEBUG: Entry - title='like the € sign...', username='joe', url='', path='', full_path_title='like the € sign...'
DEBUG: Entry - title='Test Title 1', username='joe50', url='é u'\xe9'', path='', full_path_title='Test Title 1'
DEBUG: Entry - title='Additional Attributes', username='', url='', path='', full_path_title='Additional Attributes'
DEBUG: Entry - title='Test Title 2', username='fred60', url='https://google.com', path='ȧƈƈḗƞŧḗḓ ŧḗẋŧ ƒǿř ŧḗşŧīƞɠ', full_path_title='ȧƈƈḗƞŧḗḓ ŧḗẋŧ ƒǿř ŧḗşŧīƞɠ/Test Title 2'
DEBUG: Entry - title='ȧƈƈḗƞŧḗḓ ŧḗẋŧ', username='ȧƈƈḗƞŧḗḓ', url='ȧƈƈḗƞŧḗḓ ŧḗẋŧ ƒǿř ŧḗşŧīƞɠ', path='ȧƈƈḗƞŧḗḓ ŧḗẋŧ ƒǿř ŧḗşŧīƞɠ', full_path_title='ȧƈƈḗƞŧḗḓ ŧḗẋŧ ƒǿř ŧḗşŧīƞɠ/ȧƈƈḗƞŧḗḓ ŧḗẋŧ'
DEBUG: Entry - title='Test Title', username='joe20', url='https://google.com', path='Test', full_path_title='Test/Test Title'
DEBUG: Entry - title='Reference Entry Test - Test Title 1', username='joe50', url='é u'\xe9'', path='Test', full_path_title='Test/Reference Entry Test - Test Title 1'
DEBUG: Entry - title='expiring', username='', url='', path='Test', full_path_title='Test/expiring'
DEBUG: Entry - title='keepass2 totp', username='testuser', url='https://keepass.info/', path='otp-test', full_path_title='otp-test/keepass2 totp'
DEBUG: Entry - title='keepass2 totp - more fields', username='testuser', url='https://keepass.info/', path='otp-test', full_path_title='otp-test/keepass2 totp - more fields'
DEBUG: Entry - title='keepass2 totp - multiple configs', username='testuser', url='https://keepass.info/', path='otp-test', full_path_title='otp-test/keepass2 totp - multiple configs'
DEBUG: Entry - title='Backblaze B2', username='firecat53', url='', path='Scotty', full_path_title='Scotty/Backblaze B2'
DEBUG: Entry - title='Backblaze Help', username='sam', url='', path='Scotty', full_path_title='Scotty/Backblaze Help'
DEBUG: Entry - title='Backup user SSH key', username='', url='', path='Scotty', full_path_title='Scotty/Backup user SSH key'
DEBUG: Entry - title='Duo', username='user1@domain1.tld', url='', path='Hosting/Auth', full_path_title='Hosting/Auth/Duo'
DEBUG: Entry - title='Duo', username='user2@domain2.tld', url='', path='Hosting/Auth', full_path_title='Hosting/Auth/Duo'
DEBUG: Entry - title='Duo', username='user1@domain1.tld', url='', path='Work/Auth', full_path_title='Work/Auth/Duo'
DEBUG:   -> MATCH (all terms found)
DEBUG: Entry - title='Duo', username='user2@domain2.tld', url='', path='Work/Auth', full_path_title='Work/Auth/Duo'
DEBUG: Entry - title='Duo', username='user1@domain1.tld', url='', path='Work/HR', full_path_title='Work/HR/Duo'
DEBUG:   -> MATCH (all terms found)
DEBUG: --- End of entries ---
DEBUG: Total matches: 2
Multiple entries found matching 'work user1'. Please be more specific.
  - Work/Auth/Duo (user1@domain1.tld)
  - Work/HR/Duo (user1@domain1.tld)
```

**Comment by vaygr** [comment]
Thank you! Mystery solved. It turned out I had an old module folder of keepmenu from March '25 in the PATH that somehow worked partially with this.

Fixed this, and it's all working as expected.

`keepmenu -s "duo work auth user1" -d tests/test.kdbx` returns one password.

**Comment by firecat53** [comment]
Ahhhhh, thank you! Appreciate your patience. I'll merge and cut a new release shortly-ish.

**Comment by vaygr** [comment]
I'm wondering if we should return a non-zero code when multiple entries are found. Because if `keepmenu -s` is piped into something, it would perceive output as the password, which won't be correct.

**Comment by firecat53** [comment]
Sure, sounds reasonable.

**Comment by firecat53** [comment]
Ok, give that a try.

**Comment by vaygr** [comment]
Excellent, now it's perfect.

The only thing to consider is if we want to distinguish between no entries found or multiple entries found. But if there's no error handling logic assumed overall in the app, at least yet, and an error is just an error - a.k.a. any - this is good to go.

**Comment by firecat53** [comment]
If it works for your use case, I think we can call it good. It seems like the exit code 1 would be appropriate for `--show`  for either more than one or zero entries.

**Comment by vaygr** [comment]
Yeah, sounds good to me. No reason to overcomplicate it design-wise at this point.

**Comment by The-Compiler** [comment]
Sorry for the radio silence! Seems to work fine now, even with an existing daemon running 🎉
