### ISSUE TITLE
ModuleNotFoundError: No module named 'pykeepass.kdbx_parsing'

### ISSUE THREAD

**Issue by treeshateorcs** [firecat53/keepmenu#159]
it stopped working all of a sudden

```
Traceback (most recent call last):
  File "/usr/bin/keepmenu", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/keepmenu/__main__.py", line 214, in main
    run(**args)
  File "/usr/lib/python3.11/site-packages/keepmenu/__main__.py", line 141, in run
    dmenu = DmenuRunner(server, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/keepmenu/keepmenu.py", line 301, in __init__
    self.database.kpo = get_entries(self.database)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/keepmenu/keepmenu.py", line 226, in get_entries
    from pykeepass import PyKeePass  # pylint: disable=import-outside-toplevel
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pykeepass/__init__.py", line 2, in <module>
    from .pykeepass import PyKeePass, create_database
  File "/usr/lib/python3.11/site-packages/pykeepass/pykeepass.py", line 22, in <module>
    from .kdbx_parsing import KDBX, kdf_uuids
ModuleNotFoundError: No module named 'pykeepass.kdbx_parsing'
```

keepmenu-git from the AUR, archlinux

**Comment by treeshateorcs** [comment]
it's a regression in `python-pykeepass`. works fine with v4.0.6, doesn't work with v4.0.7

**Comment by firecat53** [comment]
I'm running keepmenu just fine on NixOS using pykeepass 4.0.7. I also tried in an Arch container and it seemed to launch without any errors. Did you try to reinstall it and ensure all previous versions were uninstalled?

**Comment by treeshateorcs** [comment]
the `python-keepass` package has since been updated twice (current version is 4.0.7-3). it works fine now, sorry for keeping this issue open
