### ISSUE TITLE
Unable to use password with %

### ISSUE THREAD

**Issue by varac** [firecat53/keepmenu#17]
```
 ~/.config/keepmenu | keepmenu ed   
Traceback (most recent call last):
  File "/home/varac/.local/bin/keepmenu", line 1206, in <module>
    MANAGER = client()
  File "/home/varac/.local/bin/keepmenu", line 1032, in client
    mgr.connect()
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 489, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/varac/.local/bin/keepmenu", line 1210, in <module>
    run()
  File "/home/varac/.local/bin/keepmenu", line 1195, in run
    dmenu = DmenuRunner(server)
  File "/home/varac/.local/bin/keepmenu", line 1045, in __init__
    self.database = get_database()
  File "/home/varac/.local/bin/keepmenu", line 252, in get_database
    args = CONF.items('database')
  File "/usr/lib/python3.6/configparser.py", line 858, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.6/configparser.py", line 858, in <listcomp>
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.6/configparser.py", line 855, in <lambda>
    section, option, d[option], d)
  File "/usr/lib/python3.6/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.6/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '% ………'
```

Escaping the `%` with `%%` doesn't work neither, I get a `ChecksumError` then:

```
construct.core.ChecksumError: wrong checksum, read b'eccea587b10f3bb2e662a0f4c3e033a0dc85a73eafbac3cde82a42d455457f3d', computed b'0de2bf47f1955770e7c9663067938a7f88b21b74aa18365c768210da34452ddf'
```

(My password also contains brackets and spaces, not sure if this is related).

Also, one small documentation issue: Please document if it is possible/advised to use quotes for passwords which spaces, or if the quotes would be considered part of the password.

**Comment by firecat53** [comment]
I was able to use a password '%test []{}' in config.ini as follows:

    password_2 = %%test []{}

No quotes, just double the % sign. I'll take a look a documenting that, however the idea is to _not_ put passwords in config.ini except for testing! Extremely insecure.

**Comment by varac** [comment]
Thx, I'll give it another try.

> No quotes, just double the % sign. I'll take a look a documenting that, however the idea is to not put passwords in config.ini except for testing! Extremely insecure.

I know, just doing this as intermediate step until #16 is implemented.
