### ISSUE TITLE
Error: 'bytes' object has no attribute 'encode' after typing password

### ISSUE THREAD

**Issue by elvirolo** [firecat53/keepmenu#27]
Hello!

I get the following error after typing my password in keepmenu: Error: 'bytes' object has no attribute 'encode'

For what it's worth, it has worked in the past with the same config file.

I use it with rofi.

Distro: Arch Linux
Installed python-keepmenu-git r88.b0f7532-1 from AUR.
Relevant package versions:
rofi-1.5.2-1
python-3.7.2-3
python-pykeepass-3.0.2-2
python-pyuserinput-git-r260.1502266119.ac2d4c7-1
xdotool 3.20160805.1-2 

I have sent my config file and strace output to you by email, as I'd rather not have them available publicly.

Thanks for your great work!

**Comment by firecat53** [comment]
What do you mean "typing my password in keepmenu"? You have a gpg command in your config.ini set to automatically provide the password to open keepmenu. 

Do you mean when you select a entry from keepmenu to get typed? Does it do that with all your passwords or just one? Will it type a different field such as the username?

**Comment by elvirolo** [comment]
Sorry, my report was unclear. Here's what happens:
1). Launch "keepmenu".
2) Unlock GPG key in pinentry.
3) Error message appears. No keepass entry gets displayed.

**Comment by firecat53** [comment]
Ah, it's probably something to do with the unlock process. I use gpg-agent to keep mine unlocked so that's probably why I haven't seen that issue. I'll play with today and see if I can reproduce (at work...so maybe :) ).

**Comment by elvirolo** [comment]
Ok, thanks :) Now that you mention it, it also happens when the key is already unlocked.

**Comment by firecat53** [comment]
So you can't unlock the database at all using the gpg command? How about if you don't use password_cmd and just type your password directly? And how about actually putting your password into the config file? Just trying to see where it fails.

Do you have any Unicode characters in your password?

**Comment by elvirolo** [comment]
It works neither when I add the password in the config file, nor when I type it directly in keepmenu. My password does not contain Unicode characters, only letters, numbers and special characters. I tried with a test database with a password containing special characters and spaces in its filename, and it works fine, though.

I installed keepmenu from the AUR, but the same error is displayed when I simply run it from a git repo clone. Not using a virtualenv.

**Comment by elvirolo** [comment]
Here's the error I get when I open the db with keepmenu 0.5.5 (no error is display with 0.5.6 or 0.5.7):

`keepmenu-0.5.5>$ ./keepmenu 
xdotool version 3.20160805.1
Traceback (most recent call last):
  File "./keepmenu", line 1206, in <module>
    MANAGER = client()
  File "./keepmenu", line 1032, in client
    mgr.connect()
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 512, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./keepmenu", line 1210, in <module>
    run()
  File "./keepmenu", line 1195, in run
    dmenu = DmenuRunner(server)
  File "./keepmenu", line 1046, in __init__
    self.kpo = get_entries(self.database)
  File "./keepmenu", line 317, in get_entries
    kpo = PyKeePass(dbf, password, keyfile=keyfile)
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 28, in __init__
    self.read(password=password, keyfile=keyfile)
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 45, in read
    keyfile=keyfile
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 325, in parse_file
    return self.parse_stream(f, **contextkw)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 316, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 3663, in _parse
    return sc._parsereport(stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 2604, in _parse
    return self.func(context) if callable(self.func) else self.func
  File "/usr/lib/python3.7/site-packages/pykeepass/kdbx_parsing/kdbx4.py", line 55, in compute_transformed
    key_composite
  File "/usr/lib/python3.7/site-packages/pykeepass/kdbx_parsing/common.py", line 69, in aes_kdf
    keyfile=keyfile
  File "/usr/lib/python3.7/site-packages/pykeepass/kdbx_parsing/common.py", line 86, in compute_key_composite
    password_composite = hashlib.sha256(password.encode('utf-8')).digest()
AttributeError: 'bytes' object has no attribute 'encode'
`

**Comment by firecat53** [comment]
Try this: in the git version you downloaded, try changing line 285 to:

    passw = res[0].decode(ENC).rstrip('\n') if res[0] else passw

(just add ENC in the decode() call). Run ./keepmenu from that directory to ensure you run the changed version.

FWIW, I don't think this will work, but it's worth a try.

If it doesn't work, change your database password in keepassxc and try again with a brand new password. I know that sounds odd, but I'm having trouble figuring out where the error could be.

**Comment by elvirolo** [comment]
No luck with either suggestion, unfortunately :(

**Comment by firecat53** [comment]
Hrm. Create a new database in keepassxc and see if that one works. Maybe your database is an older Keepass version?

**Comment by elvirolo** [comment]
New DB works, so does the same one after an export/reimport to/from CSV.

**Comment by firecat53** [comment]
Are you sure the database was a keepass 2.x version and not an older 1.x version database that maybe got renamed by mistake? Pykeepass only support kdbx3 and kdbx4 databases. In any case, sounds like we've resolved the issue for you?

**Comment by elvirolo** [comment]
Yes, it is a kdbx4 database - it actually used to work fine with keepmenu. Not sure what happened. Thanks for your help and sorry for the inconvenience.

**Comment by firecat53** [comment]
No worries, glad we figured it out!

**Comment by 111lisu** [comment]
keepmenu
  File "/usr/local/bin/keepmenu", line 444
    nonlocal cmd
               ^
SyntaxError: invalid syntax

The question is what is missing

**Comment by firecat53** [comment]
@111lisu I'm sorry, I don't understand your comment. Can you please clarify?
