### ISSUE TITLE
Incorrect terminal config softlocks the daemon

### ISSUE THREAD

**Issue by iFreilicht** [firecat53/keepmenu#70]
On my machine, there is no xterm, I use kitty instead.
When launching keepass and trying to edit a note, the window disappears and trying to open keepmenu again will have no effect.
To fix this, I have to `pregp -a python | grep keep` and `kill` all PIDs that show up.

This is the error message that shows up when I run the first keepmenu instance on a terminal:

```
~$ keepmenu
xdotool version 3.20160805.1
Process DmenuRunner-2:
Traceback (most recent call last):
  File "/usr/bin/keepmenu", line 1463, in <module>
    MANAGER = client()
  File "/usr/bin/keepmenu", line 1240, in client
    mgr.connect()
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 548, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/bin/keepmenu", line 1275, in run
    self.dmenu_run()
  File "/usr/bin/keepmenu", line 1333, in dmenu_run
    self.menu_edit_entries()
  File "/usr/bin/keepmenu", line 1376, in menu_edit_entries
    edit = edit_entry(self.kpo, entry)
  File "/usr/bin/keepmenu", line 1176, in edit_entry
    sel = edit_notes(kp_entry.notes)
  File "/usr/bin/keepmenu", line 1213, in edit_notes
    call(editor)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xterm'
```
This error is of course fixed by setting `terminal = kitty` in the config, but it would be better if this error was shown to the user properly and didn't softlock the daemon.

**Comment by firecat53** [comment]
Pushed a fix to the 'develop' branch. Let me know if that works correctly for you.
