### ISSUE TITLE
"View / Type individual entries" crashes keepmenu

### ISSUE THREAD

**Issue by br-olf** [firecat53/keepmenu#79]
Since the latest Update keepmenu keeps crashing when I want to use the View / Type individual entries submenu.

OS: Arch / Manjaro Linux `Linux 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000`
Version: `aur/python-keepmenu-git r8.7418838-1 [installed: r127.81a847b-1] (5, 0.19)`
pykeepass: `community/python-pykeepass 4.0.0-1 [installed]`

Error:
```
% keepmenu
xdotool version 3.20160805.1
Process DmenuRunner-2:
Traceback (most recent call last):
  File "/usr/bin/keepmenu", line 1484, in <module>
    MANAGER = client()
  File "/usr/bin/keepmenu", line 1255, in client
    mgr.connect()
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 522, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 507, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/bin/keepmenu", line 1290, in run
    self.dmenu_run()
  File "/usr/bin/keepmenu", line 1350, in dmenu_run
    self.menu_view_type_individual_entries(hid_groups)
  File "/usr/bin/keepmenu", line 1382, in menu_view_type_individual_entries
    text = view_entry(entry)
  File "/usr/bin/keepmenu", line 1083, in view_entry
    kp_entries_b = "\n".join(fields).encode(ENC)
TypeError: sequence item 0: expected str instance, list found
```

**Comment by asimonen** [comment]
I had the same problem, but apparently upgrading to the latest python-keepmenu-git version r149.d3b901a-1 (from AUR) fixed it.

**Comment by firecat53** [comment]
@br-olf did you update to the latest git version? There were changes needed to
accomodate the python-pykeepass 4.0 upgrade.

**Comment by firecat53** [comment]
I'm going to close this for now as I'm pretty sure it's just an updating issue.  Please let me know if you need more help sorting it out.

**Comment by br-olf** [comment]
Yep, sry it was fixed by an update. Thank you
