### ISSUE TITLE
Connection refused error on launch

### ISSUE THREAD

**Issue by Nanoseb** [firecat53/keepmenu#9]
Hi,
First thank you for your tool, I can't use it yet, but it looks like a really nice piece of software. The reason why I can't use it is because jwhen running `keepmenu` just after typing my database password I get the following error:

```
Process DmenuRunner-2:
Traceback (most recent call last):
  File "/usr/bin/keepmenu", line 932, in <module>
    MANAGER = client()
  File "/usr/bin/keepmenu", line 758, in client
    mgr.connect()
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 512, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/bin/keepmenu", line 788, in run
    self.dmenu_run()
  File "/usr/bin/keepmenu", line 833, in dmenu_run
    sel = view_all_entries(options, [i for i in self.kpo.entries if not
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 73, in entries
    return self.find_entries_by_title('.*', regex=True)
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 292, in find_entries_by_title
    first=first
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 272, in find_entries
    res = self._find(keys_xp, **kwargs)
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 159, in _find
    res = self._xpath(xp, tree=group._element if group else None)
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 85, in _xpath
    tree = self.kdb.tree
AttributeError: 'KDB3Reader' object has no attribute 'tree'
```

I am using archlinux and installed keepmenu directly thanks to your aur package. Do you have an idea of what is going wrong with my setup?

**Comment by firecat53** [comment]
What version of keepass was used to create your database? Is it a keepass 1.x database or keepass 2.x? Keepmenu only works with 2.x databases (kdbx). It looks like it's trying to read a 1.x database. You can import your database into a 2.x database using keepassxc.

**Comment by Nanoseb** [comment]
Ah yes indeed, I am still using a v1 database. It works great now. 
Thanks!
